### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by tomgross** [collective/collective.timedevents#2]
@hvelarde @miohtama @sunew Can someone please make a release on pypi for Plone 5 compatibility? Or give me the rights please so I can do it myself.

I recently added Plone 5 compatibility, which was mainly incorporate with the CSRF protection.

**Comment by sunew** [comment]
@tomgross pypi username tomgross?

**Comment by tomgross** [comment]
no it is _iT0m_ (with a zero ;-)

**Comment by sunew** [comment]
@tomgross added :)
