### ISSUE TITLE
Released version doesn't contain 'configure.zcml'

### ISSUE THREAD

**Issue by lewicki** [collective/collective.timedevents#3]
That file https://pypi.python.org/packages/source/c/collective.timedevents/collective.timedevents-1.0.3.tar.gz
doesn't contain 'configure.zcml'. It means that the product is practically broken.

**Comment by laulaz** [comment]
I confirm that the package is broken since release 1.0.

**Comment by puittenbroek** [comment]
Can a new release be made that does include the configure.zcml??

**Comment by puittenbroek** [comment]
@tomgross You released 1.0.4, but I do not find any traces here?

**Comment by tomgross** [comment]
It is there:

![grafik](https://user-images.githubusercontent.com/339384/31176337-ceeb3d90-a912-11e7-8f2d-7557d377f823.png)

**Comment by puittenbroek** [comment]
Ok :) Just double checking, we were still running from a github version :scream:
